### ISSUE TITLE
Alignment-based behaviors are screwed

### ISSUE THREAD

**Issue by yarbroughw** [cs383-final/cs383-finalproject#10] opened 2015-04-27 20:20 UTC
Swarmstep works, but the other behaviors (those that use alignment weights that are >0) cause the boids to speed up ad nauseum until the program crashes (likely due to overflow of the vector components).

I think there's a bug with the alignment code... I can look at it tonight.

**Comment by hawkw** [comment] 2015-04-27 20:29
I'll check it out, too. Be nice to have this fixed by tomorrow.

**Comment by hawkw** [comment] 2015-04-27 21:39
Well, I checked our code against the formula from ["Autonomous Boids"](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.89.5700&rep=rep1&type=pdf), and it _seems_ right to me...

**Comment by hawkw** [comment] 2015-04-27 22:16
I'm really not sure why the `alignment` function uses so much CPU and makes it hang when the `centre` function works almost exactly the same way...

**Comment by hawkw** [comment] 2015-04-27 22:27
Do you suppose this is just an inherent problem caused by all the boids having the same starting velocity (because they appear never to encounter a boid who's moving slower than they are and therefore never slow down)? Do you suppose introducing jitter to the starting velocities might fix it?

**Comment by hawkw** [comment] 2015-07-04 02:24
Closed by Will in 1092490

**Closed as completed** 2015-07-04 02:24 UTC
Labels: bug
